name: Deploy to TeemioAPI
on:
  push:
   paths-ignore:
      - 'setupMongoDB.ts'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      RESEND_API_KEY: ${{secrets.RESEND_APi_KEY}}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run Tests
        run: bun test
