name: Deploy to TeemioAPI
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      RESEND_API_KEY: ${{secrets.RESEND_APi_KEY}}
      NODE_ENV: ${{secrets.NODE_ENV}}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run Tests
        run: bun test
