name: Deploy to TeemioAPI
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v3

      # Caching MongoDB binaries
      - name: Cache MongoDB binaries
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/mongodb-binaries
          key: ${{ runner.os }}-mongodb-binaries-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-mongodb-binaries-

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run Tests
        run: bun test
